jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Cosa\Instant\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        my_fos_twitter_provider:
            id: my.twitter.user

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        #login_firewall:
        #    pattern:    ^/login$
        #    anonymous:  true
        # Firewall principal pour le reste de notre site
        secured_area:
            pattern: ^/
            anonymous: ~
            fos_twitter:
                login_path: /login
                check_path: /login_check
                default_target_path: /login
                provider: my_fos_twitter_provider
            logout:
                path: /logout
                target: /login
    access_control:
        - { path: ^/login, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/login_check, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/connectTwitter, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/about, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/who_we_are, role: [IS_AUTHENTICATED_ANONYMOUSLY] }
        - { path: ^/.*, role: [ROLE_USER] }
