<?php

namespace Cosa\Instant\TimelineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InstantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InstantRepository extends EntityRepository
{

    public function getLastId()
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i.id
                 FROM CosaInstantTimelineBundle:Instant i
                 ORDER BY i.id DESC'
            )
            ->setMaxResults(1)
            ->getSingleResult();
    }

    public function findByUserNTitle($user_id,$title)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i
                 FROM CosaInstantTimelineBundle:Instant i
                 WHERE i.title=:title
                 AND i.user=:user_id
                 LIMIT 1'
            )
            ->setParameter('user_id',$user_id)
            ->setParameter('title',$title)
            ->setMaxResults(1)
            ->getResult();
    }

/*    public function getAllByUsername($username)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT i
                 FROM CosaInstantTimelineBundle:Instant i,
                      CosaInstantUserBundle:User u
                 WHERE u.username=:username
                 AND i.user=u.id
                 ORDER BY i.id ASC'
            )
            ->setParameter('username',$username)
            ->getResult();
    }*/
}
