<?php

namespace Cosa\Instant\TimelineBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TwittosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwittosRepository extends EntityRepository
{
    public function getComplete($instant_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t,u
                 FROM CosaInstantTimelineBundle:Twittos t
                 JOIN t.user u
                 WHERE t.instant=:instant_id
                 ORDER BY t.id desc'
            )
            ->setParameter('instant_id',$instant_id)
            ->getResult();
    }

    public function getTwittosToAlert($instant_id)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t,u
                 FROM CosaInstantTimelineBundle:Twittos t
                 JOIN t.user u
                 WHERE t.instant=:instant_id
                 AND t.alerted=FALSE'
            )
            ->setParameter('instant_id',$instant_id)
            ->getResult();
    }
}
