login:
    pattern: /login
    defaults: { _controller: CosaInstantUserBundle:Default:login }
cosa_instant_user_login_check:
    pattern: /login_check
    defaults: { _controller: CosaInstantUserBundle:Default:connectTwitter }
cosa_instant_user_logout:
    pattern: /logout
    defaults: { _controller: CosaInstantUserBundle:Default:logout }
connect_twitter:
    pattern: /connectTwitter
    defaults: { _controller: CosaInstantUserBundle:Default:connectTwitter }
email_validation:
    pattern: /email/validation/{token}
    defaults: { _controller: CosaInstantUserBundle:Default:emailValidation }
