#cosa_instant_timeline_homepage:
#    pattern:  /hello/{name}
#    defaults: { _controller: CosaInstantTimelineBundle:Default:index }
#CosaInstantTimelineBundle_instant:
#    resource: "@CosaInstantTimelineBundle/Resources/config/routing/instant.yml"
#    prefix:   /instant
please_confirm_email:
    pattern:  /{username}/please/confirm/your/email
    defaults: { _controller: CosaInstantTimelineBundle:Default:pleaseConfirmEmail }
instant_list:
    pattern:  /{username}/instants/{order}
    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstantList, order: undefined }
instant_new:
    pattern:  /{username}/instant/new
    defaults: { _controller: CosaInstantTimelineBundle:Instant:new }
instant_create:
    pattern:  /{username}/instant/create
    defaults: { _controller: CosaInstantTimelineBundle:Instant:create }
instant_edit:
    pattern:  /{username}/{instant_title}/edit
    defaults: { _controller: CosaInstantTimelineBundle:Instant:edit }
instant_update:
    pattern: /{instant_id}/update
    defaults: { _controller: CosaInstantTimelineBundle:Instant:update }
#insant_save:
#    pattern:  /{username}/{instant_title}/save
#    defaults: { _controller: CosaInstantTimelineBundle:Instant:save }
#instant_publish:
#    pattern:  /{username}/{instant_title}/publish
#    defaults: { _controller: CosaInstantTimelineBundle:Instant:update }
#instant_view:
#    pattern:  /{username}/{instant_title}
#    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstant }
instant_wview:
    pattern:  /{username}/{instant_title}/wview
    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstantWview }
instant_view:
    pattern:  /{username}/{instant_title}/view
    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstantView }
instant_webview:
    pattern:  /{username}/{instant_title}/webview
    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstantWebview }
instant_preview:
    pattern:  /{instant_id}/preview
    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstantPreview }
instant_preview2:
    pattern:  /{username}/{instant_title}/preview
    defaults: { _controller: CosaInstantTimelineBundle:Instant:instantPreview }
instant_embed:
    pattern:  /{username}/{instant_title}/embed
    defaults: { _controller: CosaInstantTimelineBundle:Instant:userInstantEmbed }
instant_delete:
    pattern:  /{username}/{instant_title}/delete
    defaults: { _controller: CosaInstantTimelineBundle:Instant:delete }
instant_twitter_search:
    pattern:  /twitter-search
    defaults: { _controller: CosaInstantTimelineBundle:Instant:twitterSearch }
instant_twitter_search2:
    pattern:  /twitter-search2
    defaults: { _controller: CosaInstantTimelineBundle:Instant:twitterSearch2 }
instant_geo_search:
    pattern:  /geo-search
    defaults: { _controller: CosaInstantTimelineBundle:Instant:geoSearch }
instant_add_keyword:
    pattern:  /{instant_id}/add-keyword
    defaults: { _controller: CosaInstantTimelineBundle:Instant:addKeyword }
instant_rm_keyword:
    pattern:  /remove/keyword/{keyword_id}
    defaults: { _controller: CosaInstantTimelineBundle:Instant:rmKeyword }
instant_add_twittos:
    pattern:  /{instant_id}/add-twittos
    defaults: { _controller: CosaInstantTimelineBundle:Instant:addTwittos }
instant_add_twittos2:
    pattern:  /{instant_id}/add-twittos/byUsername
    defaults: { _controller: CosaInstantTimelineBundle:Instant:addTwittos2 }
instant_rm_twittos:
    pattern:  /remove/twittos/{twittos_id}
    defaults: { _controller: CosaInstantTimelineBundle:Instant:rmTwittos }
instant_add_tweet:
    pattern:  /{instant_id}/add-tweet
    defaults: { _controller: CosaInstantTimelineBundle:Instant:addTweet }
instant_rm_tweet:
    pattern:  /remove/from/{instant_id}/tweet/{tweet_id}
    defaults: { _controller: CosaInstantTimelineBundle:Instant:rmTweet }
instant_up_twittos :
    pattern:  /update/twittos/{twittos_id}
    defaults: { _controller: CosaInstantTimelineBundle:Instant:upTwittos }
instant_cr:
    pattern: /update/instant/{instant_id}
    defaults: { _controller: CosaInstantTimelineBundle:Instant:upInstant }
instant_clear:
    pattern:  /{instant_id}/clear
    defaults: { _controller: CosaInstantTimelineBundle:Instant:clear }
instant_refresh_timeline:
    pattern:  /{instant_id}/refresh/timeline
    defaults: { _controller: CosaInstantTimelineBundle:Instant:refreshTimeline }
instant_more_tweets:
    pattern:  /{instant_id}/more/tweets
    defaults: { _controller: CosaInstantTimelineBundle:Instant:moreTweets }
instant_nb_new_tweets:
    pattern:  /{instant_id}/nb/new/tweets
    defaults: { _controller: CosaInstantTimelineBundle:Instant:nbNewTweets }
