parameters:
#    cosa_instant_timeline.example.class: Cosa\Instant\TimelineBundle\Example

services:
#    cosa_instant_timeline.example:
#        class: %cosa_instant_timeline.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
